### PR TITLE
Fix executing commands in PowerShell

### LINKED ISSUE #47: Fix constantly failing unit test on Appveyor.
One of the unit tests is consistently failing on Appveyor, I'm not sure what the problem is (haven't investigated). We need to get this build passing again.

### PR DESCRIPTION
**Pull request by zaeleus**
This fixes tests failing on Windows by replacing node-powershell with a
simple module to shell out to PowerShell. It also avoids having to deal
with EOI, which previously would be removed anywhere from the output.

Fixes #47

### CODE REVIEW

**Comment by claymcleod** [comment]
For quite a few of the processes, we use an asyncronous process spawning so that we can do things like monitor upload or download statistics while the process is running, etc. Looking at [this code](https://github.com/stjude/sjcloud-data-transfer-app/pull/50/files#diff-c5fe22f7ae6017ecb1e553090d5b2a4eL207), it seems like we are using the command in an async way, which is being eliminated in this pull request. I suspect all of this functionality would break. I'd ask you to test uploading or downloading a file to see if the progress bars update correctly.

Typically, we write these kinds of functions in pairs: (1) for async and (2) for sync. That way, it's just more convenient to be used. 

We originally had our own homegrown solution, then we turned to this module. I remember there being quite a bit of thought that went into that decision. So if we are going to flip back to homegrown, I think we just need to make sure that we have all of our functionality bases covered.

**Comment by zaeleus** [comment]
I'll take a closer look. While the original code does use async APIs, it buffers the output [until execution ends](https://github.com/stjude/sjcloud-data-transfer-app/blob/bd62c705361e8b4b1227f59d8f04ce4efb860548/app/src/backend/utils.ts#L232-L234), meaning it behaves like a synchronous call.

**Comment by claymcleod** [comment]
Sure. It defers the inner callback piece until process completion, [but it returns the process](https://github.com/stjude/sjcloud-data-transfer-app/blob/bd62c705361e8b4b1227f59d8f04ce4efb860548/app/src/backend/utils.ts#L244) after invocation. Those process IDs are passed through `queue.ts` and then eventually used [in the frontend](https://github.com/stjude/sjcloud-data-transfer-app/blob/bd62c705361e8b4b1227f59d8f04ce4efb860548/app/src/frontend/bootstrap-backend.js#L13) to manage things like the file download/upload progress, etc.

**Comment by claymcleod** [comment]
Actually, looks like `queue.ts` is controlling the frontend from inside that module. I'm a little fuzzy on the details but definitely something going on.

File: app/src/backend/powershell.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+const EXE = 'powershell.exe';
+const DEFAULT_ARGS = [
+  '-ExecutionPolicy',
+  'Bypass',
+  '-NoProfile',
+  '-NonInteractive',
+  '-Command',
+];
+
+const escapeCommand = (s: string): string => s.replace(/"/g, '\\"');
```
Comment (claymcleod) [inline app/src/backend/powershell.ts]: Feels like there is the capacity for this to be non-exhaustive. Not sure if there is some builtin that would be better? Regardless, we might not hit that in practice. If you feel good about it, I'm fine with signing off.

Comment (zaeleus) [reply app/src/backend/powershell.ts]: Since this just shells out to PowerShell, it should be assumed that anything you pass it behaves as if you're writing it in the prompt, meaning it's up to the caller to escape anything. Automatic escaping of double quotes is only necessary because the argument for the command has to be in double quotes.

**Comment by zaeleus** [comment]
Docs added. `ChildProcess` objects were also readded.

**Comment by claymcleod** [comment]
Have you tested to make sure that this will upload and download a file on Windows? If so, we can merge.

**Comment by zaeleus** [comment]
I'll work with @jsunny23 tomorrow to try some manual tests. Since this patch maintains the preexisting architecture, I'd also expect it to behave the same.
